### ISSUE TITLE
Checking Out

### ISSUE THREAD

**Issue by rwarbelow** [kristindiannefoss/little_shop#49]
Background: An existing user and a cart with items
      As a visitor
      When I add items to my cart
      And I visit "/cart"
      And I click "Login or Register to Checkout"
      Then I should be required to login or complete registration
      When I am logged in I should be taken back to my cart
      And when I click "Checkout"
      Then the order should be placed
      And my current page should be "/orders"
      And I should see a message "Order was successfully placed"
      And I should see the order I just placed in a table

**Comment by notmarkmiranda** [comment]
orders table, order_items table are populated from the session[:cart]

hit checkout button, creates a new entry in the order table
@cart.contents {"2"=> 5, "3" => 1}

order_items
id=2, item_id = 2 , order_id = 4, qty =5
id=3, item_id = 3, order_id = 4, qty = 1
