### ISSUE TITLE
Find Bootstrap Templates

### ISSUE THREAD

**Issue by kristindiannefoss** [kristindiannefoss/little_shop#64]
Research e-commerce templates:

Views: index and show, cart and confirmation page can build off of these.
Profile page: similar format.

**Comment by notmarkmiranda** [comment]
* Boxie
 * demo - https://boxie.lemonstand.com/
 * source - https://github.com/lemonstand/lscloud-theme-boxie

**Comment by notmarkmiranda** [comment]
* Hype
 * demo - https://hype.lemonstand.com/
 * source - https://github.com/lemonstand/lscloud-theme-hype

**Comment by notmarkmiranda** [comment]
* Whity
 * demo - http://p.w3layouts.com/demos/adidas/web/
 * source - on my computer

**Comment by notmarkmiranda** [comment]
* Fame
 * demo - http://readytheme.net/demo/?item=fame
* source - on my computer

**Comment by deborahleehamel** [comment]
Brave
 - http://wrapbootstrap.com/preview/WB0C06H5D

Specific free templates for shop item and shopping page here:
 - http://startbootstrap.com/template-categories/all/
